sudo: true
dist: trusty

env:
  global:
        - COMMIT=${TRAVIS_COMMIT::8}
jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH" ; fi`
      - export REPO="$DOCKER_USERNAME/$DOCKER_IMAGE"
      - docker build --rm -f Dockerfile -t "$REPO:$COMMIT" .
      - docker images
      - docker tag "$REPO:$COMMIT" "$REPO:$TAG"
      - docker tag "$REPO:$COMMIT" "$REPO:travis-$TRAVIS_BUILD_NUMBER"
      - docker push $REPO
    - stage: test
      script: 
      - docker run --rm $DOCKER_USERNAME/$DOCKER_IMAGE python build.py ./build.py -d codal-stm32-iot-node
