sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build --rm -f Dockerfile -t "$DOCKER_IMAGE":latest .
      - docker images
      - docker tag  $DOCKER_IMAGE:latest $DOCKER_USERNAME/$DOCKER_IMAGE:latest
      - docker push $DOCKER_USERNAME/$DOCKER_IMAGE:latest
    - stage: test
      script: 
      - docker run --rm $DOCKER_USERNAME/$DOCKER_IMAGE python build.py -t
